/**
 * Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MonthInfo { 
    monthName?: string | null;
    offen?: number;
    bezahlt?: number;
    in_Arbeit?: number;
    erledigt?: number;
}

