/**
 * Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderDtoIn { 
    inputDate?: string;
    deliveryDate?: string;
    paymentDate?: string;
    documentNr?: number;
    brutto?: number;
    netto?: number;
    tax?: number;
    fK_CustomerId?: number;
    bill?: number;
    po?: string | null;
    fK_StatusId?: number;
    uid?: string | null;
}

