/**
 * Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface YearInfoDto { 
    sumBrutto?: number | null;
    sumNetto?: number | null;
    sumTax?: number | null;
    verrechnetBrutto?: number | null;
    verrechnetNetto?: number | null;
    bezahltBrutto?: number | null;
    bezahltNetto?: number | null;
    erledigtBrutto?: number | null;
    erledigtNetto?: number | null;
    inArbeitBrutto?: number | null;
    inArbeitNetto?: number | null;
}

